import { css } from '@emotion/css'
import Head from 'next/head'

const test = css`
  color: red;
`

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className={test}>TEST VANILLA WITH NEXT SSR</h1>
      </main>
    </>
  )
}
